version: "2.0"
services:
  postgres:
    image: postgres:9.5
    environment:
      POSTGRES_DB: example_development
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
  rails:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    restart: always
volumes:
  pg_data: {}
